# Generated by Django 2.2.8 on 2020-07-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeZoneTaskapp', '0002_auto_20200714_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='user',
        ),
    ]
