# Generated by Django 2.2.8 on 2020-07-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeZoneTaskapp', '0003_remove_country_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='task_type',
        ),
        migrations.AddField(
            model_name='country',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
