# Generated by Django 2.2.8 on 2020-07-15 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeZoneTaskapp', '0006_auto_20200714_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_day', models.CharField(choices=[('None', 'None'), ('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], default='none', max_length=50)),
                ('end_day', models.CharField(choices=[('None', 'None'), ('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], default='none', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'task_type', 'country')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='task_time',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='task_time',
            name='country',
        ),
        migrations.RemoveField(
            model_name='task_time',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='task_time',
            name='user',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Task_Time',
        ),
        migrations.DeleteModel(
            name='Task_Type',
        ),
    ]
